import fs from "node:fs";

const HASTE_HEALTH_URL =
  process.env.HASTE_HEALTH_URL ?? "http://localhost:3000";
const HASTE_HEALTH_TENANT = process.env.HASTE_HEALTH_TENANT ?? "my-health";
const HASTE_HEALTH_PROJECT = process.env.HASTE_HEALTH_PROJECT ?? "system";
const HASTE_HEALTH_USERNAME = process.env.HASTE_HEALTH_USERNAME;
const HASTE_HEALTH_PASSWORD = process.env.HASTE_HEALTH_PASSWORD;

if (!HASTE_HEALTH_USERNAME || !HASTE_HEALTH_PASSWORD) {
  throw new Error(
    "HASTE_HEALTH_USERNAME and HASTE_HEALTH_PASSWORD must be set (see .env.example). " +
      "Run with `pnpm node --env-file-if-exists=.env generate.mjs mcp`.",
  );
}

const fhirBaseUrl = `${HASTE_HEALTH_URL}/w/${HASTE_HEALTH_TENANT}/${HASTE_HEALTH_PROJECT}/api/v1/fhir`;
const credentials = `${HASTE_HEALTH_USERNAME}:${HASTE_HEALTH_PASSWORD}`;
const authHeader = `Basic ${Buffer.from(credentials).toString("base64")}`;

async function fetchAllResources(resourceType) {
  const resources = [];
  let url = `${fhirBaseUrl}/${resourceType}?_count=10000`;

  while (url) {
    const response = await fetch(url, {
      headers: { Authorization: authHeader },
    });
    if (!response.ok) {
      throw new Error(
        `Failed to fetch ${resourceType} from ${url}: ${response.status} ${response.statusText}`,
      );
    }
    const bundle = await response.json();
    resources.push(...(bundle.entry ?? []).map((entry) => entry.resource));
    url = bundle.link?.find((link) => link.relation === "next")?.url;
  }

  return resources;
}

const mcpUrl = `${HASTE_HEALTH_URL}/w/${HASTE_HEALTH_TENANT}/${HASTE_HEALTH_PROJECT}/api/v1/mcp`;

async function fetchMcpTools() {
  const response = await fetch(mcpUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: authHeader,
    },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/list" }),
  });
  if (!response.ok) {
    throw new Error(
      `Failed to fetch MCP tools from ${mcpUrl}: ${response.status} ${response.statusText}`,
    );
  }
  const body = await response.json();
  if (body.error) {
    throw new Error(`MCP tools/list returned an error: ${body.error.message}`);
  }
  return body.result.tools;
}

async function generateMcpDocumentation() {
  const tools = await fetchMcpTools();
  fs.mkdirSync("./static/mcp", { recursive: true });
  fs.writeFileSync("./static/mcp/tools.json", JSON.stringify(tools, null, 2));
}

switch (process.argv[2]) {
  case "mcp": {
    await generateMcpDocumentation();
    break;
  }
  default: {
    throw new Error(
      "Invalid argument. Please provide 'mcp' as an argument (the FHIR model is generated by scripts/generate-fhir-model.mjs).",
    );
  }
}
