import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Overview</span>',
    },
    { type: "autogenerated", dirName: "Overview" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Getting Started</span>',
    },
    { type: "autogenerated", dirName: "Getting Started" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Core Concepts</span>',
    },
    { type: "autogenerated", dirName: "Core Concepts" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">API & SDKs</span>',
    },
    { type: "autogenerated", dirName: "APIs & SDKs" },

    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Integrations</span>',
    },
    { type: "autogenerated", dirName: "Integration" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Tutorials & examples</span>',
    },
    { type: "autogenerated", dirName: "Tutorials & examples" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Reference</span>',
    },
    { type: "autogenerated", dirName: "Reference" },
  ],
};

export default sidebars;
