import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Getting Started</span>',
    },
    { type: "autogenerated", dirName: "Getting Started" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">API</span>',
    },
    { type: "autogenerated", dirName: "API" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Authentication</span>',
    },
    { type: "autogenerated", dirName: "Authentication" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Authorization</span>',
    },
    { type: "autogenerated", dirName: "Authorization" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Integration</span>',
    },
    { type: "autogenerated", dirName: "Integration" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Guides</span>',
    },
    { type: "autogenerated", dirName: "Guides" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Additional Tools</span>',
    },
    { type: "autogenerated", dirName: "Additional Tools" },
  ],
};

export default sidebars;
