name: Release Docker
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: hastehealth/hastehealth
  ADMIN_APP_IMAGE_NAME: hastehealth/admin-app

jobs:
  server:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: "write"
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $ --password-stdin
      - uses: "google-github-actions/auth@v3"
        with:
          project_id: ${{ vars.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ vars.GAR_LOCATION }}-docker.pkg.dev
      - name: Compute image names
        id: vars
        run: |
          IMAGE_NAME=$(echo $SERVER_IMAGE_NAME | tr '[A-Z]' '[a-z]')
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          GCP_IMAGE_ID=${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{vars.GAR_REPOSITORY}}/hastehealth

          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          GCP_IMAGE_ID=$(echo $GCP_IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$GITHUB_REF_NAME

          echo "image_id=$IMAGE_ID" >> "$GITHUB_OUTPUT"
          echo "gcp_image_id=$GCP_IMAGE_ID" >> "$GITHUB_OUTPUT"
      - name: Build and Publish Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/haste-health.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.vars.outputs.gcp_image_id }}:latest
            ${{ steps.vars.outputs.gcp_image_id }}:${{ github.ref_name }}
            ${{ steps.vars.outputs.image_id }}:${{ github.ref_name }}
            ${{ steps.vars.outputs.image_id }}:latest
          labels: |
            runnumber=${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  admin-app:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $ --password-stdin
      - name: Compute image names
        id: vars
        run: |
          IMAGE_NAME=$(echo $ADMIN_APP_IMAGE_NAME | tr '[A-Z]' '[a-z]')
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$GITHUB_REF_NAME

          echo "image_id=$IMAGE_ID" >> "$GITHUB_OUTPUT"
      - name: Build and Publish Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/admin-app/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.vars.outputs.image_id }}:${{ github.ref_name }}
            ${{ steps.vars.outputs.image_id }}:latest
          labels: |
            runnumber=${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
